services:
  drupal:
    image: drupal:9
    ports:
      - '8080:80'
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/wwww/html/sites
      - drupal-themes:/var/www/html/themes

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=po12345
      - POSTGRES_DB=drupal
      - POSTGRES_USER=sa
    volumes:
      - drupal-psql:/var/lib/postgresql/data

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-psql: